### ISSUE TITLE
Basic indications

### ISSUE THREAD

**Issue by jacmaes** [justb3a/processwire-feuser#1]
Hi Bea, 
I know this module is not ready for release, but whenever you have a chance, could you give us some basic indications on how to use it? Thanks! It looks like it could prove very useful to the PW community, starting with me ;-)

**Comment by justb3a** [comment]
hi,
since starting this repository Ryan Cramer startet a similar module to handle login and registration: https://modules.processwire.com/modules/login-register/. So I thought it would be better to use this one, therefore I just added a really rough readme.

**Comment by jacmaes** [comment]
Thanks Bea for the quick readme. I’m fully aware of Ryan’s module but it hasn’t been updated since its initial release and it’s too buggy to be used in production (check the issues).
