### ISSUE TITLE
Improvements to login function

### ISSUE THREAD

**Issue by jacmaes** [justb3a/processwire-feuser#2]
This should probably be a pull request, but let me just offer some changes to the login function, starting on line 83. You have: 

```
if ($this->session->login($username, $pass)) {
     // login successful
     $this->session->redirect($this->getRedirectTo($redirectTo));

   }
```

This causes a WireException (internal server error in my case) if there are multiple failed login attempts, due to ProcessWire's login throttle. Soma explains the problem and [proposes some code to remedy this](https://processwire.com/talk/topic/107-custom-login/?do=findComment&comment=58627). 

If we combine this code with yours, I've come up with the following that works great, and has the additional benefit of outputting error messages if the login is not sucessful (either a personalized message such as "Login failed…" or PW's login throttle message). 

```
    try {
          $u = $this->session->login($username, $pass);
          if($u && $u->id){
             $this->session->redirect($this->getRedirectTo($redirectTo));
          } else {
             $this->session->login_error = __('Login failed. Please try again.');
          }
      } catch(WireException $e){ // in case of multiple false login
         $this->session->login_error = $e->getMessage(); // get the error message
      }
```

Finally, on line 33, the URL to your Github repo is wrong. 

Thanks for your great work!

**Comment by justb3a** [comment]
Thanks a lot. I've adjusted the login functionality accordingly.
